import React from 'react';

var SelectSize = (props) => {
  var sizes = Object.keys(props.sizesAndAmounts);
  // NOTE: props.sizesAndAmounts is generated by the getStock helpers
  if (!sizes.length) {
    return (
      <div>
        <select disabled>
          <option>OUT OF STOCK</option>
        </select>
      </div>
    );
  } else {

    return (
      <div>
        {/* TODO project requirement: if none of selected style in stock, the drowdown should become disabled and read "OUT OF STOCK" */}
        <p id="reminder-to-select-size"></p> {/* insert text here if user tries adding to cart before selecting */}
        <select onChange={props.handleSizeSelection} >
          <option>Select size</option>
          {sizes.map((size) => {
            return (<option value={size}>{size}</option>);
          })}
        </select>
      </div>
    );
  }
};


export default SelectSize;

